//! `slcr render [FILE] [-o PATH] [--force] [--expect-no-diff]`.
//!
//! What the canon example renders to is pinned byte for byte by
//! `tests/fixtures/todo-api.md`; these tests pin what the command reports
//! and which files it writes.

use insta_cmd::assert_cmd_snapshot;

use super::{TODO_API_MD, TODO_API_YAML, Workspace, with_violation, with_warning};

/// A workspace holding the canon example at the well-known path.
fn canon() -> Workspace {
    let workspace = Workspace::new();
    workspace.file("SPEC.slcr.yml", TODO_API_YAML);
    workspace
}

#[test]
fn render_help() {
    assert_cmd_snapshot!(Workspace::new().slcr(&["render", "--help"]));
}

#[test]
fn render_writes_the_markdown_beside_the_well_known_file() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render"]));
    assert_eq!(workspace.files(), ["SPEC.md", "SPEC.slcr.yml"]);
    assert_eq!(workspace.read("SPEC.md"), TODO_API_MD);
}

#[test]
fn render_names_the_markdown_after_the_file() {
    let workspace = Workspace::new();
    workspace.file("specs/todo-api.spec.yaml", TODO_API_YAML);
    assert_cmd_snapshot!(workspace.slcr(&["render", "specs/todo-api.spec.yaml"]));
    assert_eq!(workspace.read("specs/todo-api.md"), TODO_API_MD);
}

#[test]
fn render_leaves_an_up_to_date_output_alone() {
    let workspace = canon();
    workspace.file("SPEC.md", TODO_API_MD);
    assert_cmd_snapshot!(workspace.slcr(&["render"]));
}

#[test]
fn render_writes_to_the_output() {
    let workspace = canon();
    workspace.dir("docs");
    assert_cmd_snapshot!(workspace.slcr(&["render", "--output", "docs/API.md"]));
    assert_eq!(workspace.files(), ["SPEC.slcr.yml", "docs/API.md"]);
    assert_eq!(workspace.read("docs/API.md"), TODO_API_MD);
}

#[test]
fn render_writes_to_stdout() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render", "-o", "-"]));
    assert_eq!(workspace.files(), ["SPEC.slcr.yml"]);
}

#[test]
fn render_replaces_its_own_earlier_output() {
    let workspace = canon();
    workspace.file(
        "SPEC.md",
        "<!-- Generated by slcr from the todo-api specification. -->\n\nStale.\n",
    );
    assert_cmd_snapshot!(workspace.slcr(&["render"]));
    assert_eq!(workspace.read("SPEC.md"), TODO_API_MD);
}

#[test]
fn render_replaces_a_file_it_did_not_render_only_by_force() {
    let workspace = canon();
    workspace.file("SPEC.md", "# Hand-written\n");
    assert_cmd_snapshot!("refused", workspace.slcr(&["render"]));
    assert_eq!(workspace.read("SPEC.md"), "# Hand-written\n");
    assert_cmd_snapshot!("forced", workspace.slcr(&["render", "--force"]));
    assert_eq!(workspace.read("SPEC.md"), TODO_API_MD);
}

#[test]
fn render_reports_warnings_and_renders_anyway() {
    let workspace = Workspace::new();
    workspace.file("todo-api.yaml", with_warning());
    assert_cmd_snapshot!(workspace.slcr(&["render", "todo-api.yaml"]));
    assert!(
        workspace
            .read("todo-api.md")
            .contains("The endpoint accepts GET")
    );
}

#[test]
fn render_refuses_a_specification_that_breaks_its_invariants() {
    let workspace = Workspace::new();
    workspace.file("todo-api.yaml", with_violation());
    assert_cmd_snapshot!(workspace.slcr(&["render", "todo-api.yaml"]));
    assert_eq!(workspace.files(), ["todo-api.yaml"]);
}

#[test]
fn render_never_writes_over_the_requirements_file() {
    let workspace = canon();
    let args = ["render", "--output", "./SPEC.slcr.yml", "--force"];
    assert_cmd_snapshot!(workspace.slcr(&args));
    assert_eq!(workspace.read("SPEC.slcr.yml"), TODO_API_YAML);
}

#[test]
fn render_needs_an_output_for_a_file_named_only_by_its_suffix() {
    let workspace = Workspace::new();
    workspace.file(".spec.yaml", TODO_API_YAML);
    assert_cmd_snapshot!(workspace.slcr(&["render", ".spec.yaml"]));
}

#[test]
fn render_does_not_create_a_missing_directory() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render", "-o", "docs/SPEC.md"]));
    assert_eq!(workspace.files(), ["SPEC.slcr.yml"]);
}

#[test]
fn render_reports_a_missing_file() {
    assert_cmd_snapshot!(Workspace::new().slcr(&["render"]));
}

#[test]
fn render_rejects_an_unsupported_format() {
    let workspace = Workspace::new();
    workspace.file("SPEC.md", TODO_API_MD);
    assert_cmd_snapshot!(workspace.slcr(&["render", "SPEC.md"]));
}

#[test]
fn render_takes_only_one_file() {
    assert_cmd_snapshot!(Workspace::new().slcr(&["render", "a.yaml", "b.yaml"]));
}

#[test]
fn expect_no_diff_passes_an_up_to_date_output() {
    let workspace = canon();
    workspace.file("SPEC.md", TODO_API_MD);
    assert_cmd_snapshot!(workspace.slcr(&["render", "--expect-no-diff"]));
}

#[test]
fn expect_no_diff_compares_the_output() {
    let workspace = canon();
    workspace.file("docs/API.md", TODO_API_MD);
    let args = ["render", "--expect-no-diff", "--output", "docs/API.md"];
    assert_cmd_snapshot!(workspace.slcr(&args));
}

#[test]
fn expect_no_diff_fails_on_a_missing_output() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render", "--expect-no-diff"]));
    assert_eq!(workspace.files(), ["SPEC.slcr.yml"]);
}

#[test]
fn expect_no_diff_fails_on_a_stale_output() {
    let workspace = canon();
    let stale = TODO_API_MD.replace("Persistence assumptions.", "Old assumptions.");
    workspace.file("SPEC.md", &stale);
    assert_cmd_snapshot!(workspace.slcr(&["render", "--expect-no-diff"]));
    assert_eq!(workspace.read("SPEC.md"), stale);
}

#[test]
fn expect_no_diff_cannot_compare_stdout() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render", "--expect-no-diff", "-o", "-"]));
}

#[test]
fn expect_no_diff_conflicts_with_force() {
    let workspace = canon();
    assert_cmd_snapshot!(workspace.slcr(&["render", "--expect-no-diff", "--force"]));
}
