//! The canonical Markdown rendering of a specification, per section 8 of the
//! SLCR design document: one deterministic document per specification that
//! reads top to bottom.
//!
//! The same graph always renders to the same bytes. Headings follow the
//! containment tree, siblings keep their serialized order, and the Glossary
//! comes last, alphabetized. IDs never appear in the visible text; each node
//! is preceded by a hidden anchor carrying its ID, which cross-references
//! link to.

use std::collections::HashMap;
use std::fmt::{self, Display};

use blocks::Blocks;
use inline::{anchor, escape, escape_html, link};

use crate::spec::check;
use crate::spec::graph::SlcrRequirementsDocument;
use crate::spec::id::{DependencyId, RequirementId, SectionId, TermId};
use crate::spec::node::{Refinement, Requirement, Section, SectionChild, Term};
use crate::spec::text::Title;

mod blocks;
mod inline;

/// How every rendered document begins, so that a file that begins any other
/// way is known not to have been rendered.
const GENERATED_PREFIX: &str = "<!-- Generated by slcr ";

/// The deepest heading Markdown has. Deeper nodes render as bold numbered
/// paragraphs instead.
const DEEPEST_HEADING: usize = 6;

/// Render `graph` as Markdown.
pub(crate) fn document(graph: &SlcrRequirementsDocument) -> String {
    Renderer::new(graph).render()
}

/// Whether `contents` begins as a rendered document does, which marks a file
/// that may be replaced by rendering again.
pub(crate) fn is_rendered(contents: &[u8]) -> bool {
    contents.starts_with(GENERATED_PREFIX.as_bytes())
}

/// The position of a node in the containment tree: empty for the root, and
/// otherwise each ancestor's 1-based position among its siblings, ending
/// with the node's own.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct Number(Vec<usize>);

impl Number {
    /// The number of this node's `position`th child, counting from 1.
    fn child(&self, position: usize) -> Self {
        let mut parts = self.0.clone();
        parts.push(position);
        Self(parts)
    }

    /// How far below the root the node is.
    fn depth(&self) -> usize {
        self.0.len()
    }
}

impl Display for Number {
    /// `2.` at the top level, then `2.1`, `2.1.3`, and so on.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let parts: Vec<String> = self.0.iter().map(ToString::to_string).collect();
        f.write_str(&parts.join("."))?;
        if parts.len() == 1 {
            f.write_str(".")?;
        }
        Ok(())
    }
}

/// Renders one document, with the lookups that cross-references need.
struct Renderer<'a> {
    graph: &'a SlcrRequirementsDocument,
    /// Every Section's title, the Glossary's included.
    sections: HashMap<SectionId, &'a Title>,
    requirements: HashMap<RequirementId, &'a Requirement>,
    terms: HashMap<TermId, &'a Term>,
    /// The requirements that refine each requirement, in document order.
    refiners: HashMap<RequirementId, Vec<&'a Requirement>>,
    blocks: Blocks,
}

impl<'a> Renderer<'a> {
    fn new(graph: &'a SlcrRequirementsDocument) -> Self {
        let glossary = graph.glossary();
        let sections = graph
            .sections()
            .into_iter()
            .map(|section| (*section.id(), section.title()))
            .chain([(*glossary.id(), glossary.title())])
            .collect();
        let requirements = graph.requirements();
        let refiners = check::refiners(&requirements);
        let requirements = requirements
            .into_iter()
            .map(|requirement| (*requirement.id(), requirement))
            .collect();
        let terms = glossary
            .terms()
            .iter()
            .map(|term| (*term.id(), term))
            .collect();
        Self {
            graph,
            sections,
            requirements,
            terms,
            refiners,
            blocks: Blocks::new(),
        }
    }

    fn render(mut self) -> String {
        self.blocks.push(&format!(
            "{GENERATED_PREFIX}from the {} specification. Do not edit: change the \
             specification and run `slcr render`. -->",
            self.graph.spec().name()
        ));
        let root = self.graph.root();
        self.section(root, &Number::default());
        // The Glossary is logically the root's last child.
        self.glossary(&Number::default().child(root.children().len() + 1));
        self.blocks.finish()
    }

    /// The hidden anchor and the numbered heading of a node, or a bold
    /// numbered paragraph below the deepest heading.
    fn heading(&mut self, id: impl Display, number: &Number, title: &Title) {
        let title = escape(title.as_str());
        let text = if number.depth() == 0 {
            title
        } else {
            format!("{number} {title}")
        };
        let level = number.depth() + 1;
        let heading = if level <= DEEPEST_HEADING {
            format!("{} {text}", "#".repeat(level))
        } else {
            format!("**{text}**")
        };
        self.blocks.push(&format!("{}\n{heading}", anchor(id)));
    }

    fn section(&mut self, section: &'a Section, number: &Number) {
        self.heading(section.id(), number, section.title());
        if let Some(body) = section.body() {
            self.blocks.prose(body);
        }
        self.terms_line(section.uses_term());
        for (index, child) in section.children().iter().enumerate() {
            let number = number.child(index + 1);
            match child {
                SectionChild::Section(child) => self.section(child, &number),
                SectionChild::Requirement(child) => self.requirement(child, &number, None),
            }
        }
    }

    /// Render `requirement`, whose containment parent is the requirement
    /// `parent`, or a Section if `None`.
    fn requirement(
        &mut self,
        requirement: &'a Requirement,
        number: &Number,
        parent: Option<RequirementId>,
    ) {
        let id = *requirement.id();
        self.heading(id, number, requirement.title());
        self.blocks.prose(requirement.body());
        if let Some(rationale) = requirement.rationale() {
            self.labeled("Rationale", rationale.as_str());
        }
        self.refinement(requirement);

        // The containment parent is plain from the document's structure.
        let refines: Vec<String> = requirement
            .refines()
            .iter()
            .filter(|target| Some(**target) != parent)
            .map(|target| self.requirement_link(*target))
            .collect();
        self.labeled("Refines", &refines.join(", "));

        let depends_on: Vec<String> = requirement
            .depends_on()
            .iter()
            .map(|target| self.dependency_link(*target))
            .collect();
        self.labeled("Depends on", &depends_on.join(", "));

        self.terms_line(requirement.uses_term());

        let criteria = requirement.acceptance_criteria();
        if !criteria.is_empty() {
            self.blocks.push("*Acceptance criteria:*");
            for criterion in criteria {
                self.blocks.push(&format!(
                    "{}**{}**",
                    anchor(criterion.id()),
                    escape(criterion.title().as_str())
                ));
                self.blocks.prose(criterion.body());
            }
        }

        for (index, child) in requirement.children().iter().enumerate() {
            self.requirement(child, &number.child(index + 1), Some(id));
        }
    }

    /// The refinement sentence, listing every requirement that refines
    /// `requirement`, wherever it is housed, in document order.
    fn refinement(&mut self, requirement: &Requirement) {
        let Some(refinement) = requirement.refinement() else {
            return;
        };
        let Some(refiners) = self.refiners.get(requirement.id()) else {
            return;
        };
        let sentence = match refinement {
            Refinement::And => "All of the following must hold:",
            Refinement::Or => "At least one of the following must hold:",
            Refinement::Xor => "Exactly one of the following must hold:",
        };
        let items: Vec<String> = refiners
            .iter()
            .map(|refiner| format!("- {}", link(refiner.title(), refiner.id())))
            .collect();
        self.blocks.push(sentence);
        self.blocks.push(&items.join("\n"));
    }

    fn terms_line(&mut self, terms: &[TermId]) {
        let links: Vec<String> = terms.iter().map(|term| self.term_link(*term)).collect();
        self.labeled("Terms", &links.join(", "));
    }

    /// A paragraph of `text` after an italic `label`, unless `text` is
    /// empty.
    fn labeled(&mut self, label: &str, text: &str) {
        let text = blocks::normalize(text);
        if !text.is_empty() {
            self.blocks.push(&format!("*{label}:* {text}"));
        }
    }

    fn glossary(&mut self, number: &Number) {
        let glossary = self.graph.glossary();
        self.heading(glossary.id(), number, glossary.title());
        if let Some(body) = glossary.body() {
            self.blocks.prose(body);
        }
        let mut terms: Vec<&Term> = glossary.terms().iter().collect();
        terms.sort_by_cached_key(|term| {
            let title = term.title().as_str();
            (title.to_lowercase(), title.to_owned(), *term.id())
        });

        if terms.is_empty() {
            return;
        }

        // CommonMark has no definition list, so the Glossary is an HTML one
        // whose definitions are Markdown, set off by blank lines.
        for (index, term) in terms.into_iter().enumerate() {
            // Each term's tags close the previous term's definition.
            let opening = if index == 0 { "<dl>" } else { "</dd>" };
            self.blocks.push(&format!(
                "{opening}\n<dt>{}{}</dt>\n<dd>",
                anchor(term.id()),
                escape_html(term.title().as_str())
            ));
            let aliases: Vec<String> = term
                .aliases()
                .iter()
                .map(|alias| escape(alias.as_str()))
                .collect();
            self.labeled("Also called", &aliases.join(", "));
            self.blocks.prose(term.definition());
        }
        self.blocks.push("</dd>\n</dl>");
    }

    /// A link to the requirement `id`, or its bare ID if no such
    /// requirement exists, which only an unchecked document allows.
    fn requirement_link(&self, id: RequirementId) -> String {
        self.requirements.get(&id).map_or_else(
            || id.to_string(),
            |requirement| link(requirement.title(), id),
        )
    }

    fn dependency_link(&self, id: DependencyId) -> String {
        match id {
            DependencyId::Requirement(id) => self.requirement_link(id),
            DependencyId::Section(id) => self
                .sections
                .get(&id)
                .map_or_else(|| id.to_string(), |title| link(title, id)),
        }
    }

    fn term_link(&self, id: TermId) -> String {
        self.terms
            .get(&id)
            .map_or_else(|| id.to_string(), |term| link(term.title(), id))
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;
    use std::path::Path;

    use pulldown_cmark::{Event, HeadingLevel, Options, Parser, Tag};
    use serde_json::{Value, json};

    use super::*;
    use crate::fs::format::Format;
    use crate::spec::graph::UncheckedDocument;
    use crate::spec::text::SpecName;

    const TODO_API_JSON: &str = include_str!("../../tests/fixtures/todo-api.spec.json");
    const TODO_API_YAML: &str = include_str!("../../tests/fixtures/todo-api.spec.yaml");
    const TODO_API_TOML: &str = include_str!("../../tests/fixtures/todo-api.spec.toml");
    /// What the canon example renders to.
    const TODO_API_MD: &str = include_str!("../../tests/fixtures/todo-api.md");

    fn canon() -> SlcrRequirementsDocument {
        serde_json::from_str(TODO_API_JSON).unwrap()
    }

    /// A checked document whose root, SEC-001 "Root", contains `children`,
    /// and whose Glossary, SEC-900, holds `terms`.
    fn spec(children: Value, terms: Value) -> SlcrRequirementsDocument {
        serde_json::from_value(spec_value(children, terms)).unwrap()
    }

    fn spec_value(children: Value, terms: Value) -> Value {
        let mut root = json!({ "kind": "section", "id": "SEC-001", "title": "Root" });
        if children != json!([]) {
            root["children"] = children;
        }
        let mut glossary = json!({ "kind": "section", "id": "SEC-900", "title": "Glossary" });
        if terms != json!([]) {
            glossary["terms"] = terms;
        }
        json!({
            "formatVersion": "1",
            "spec": { "name": "todo-api" },
            "root": root,
            "glossary": glossary,
        })
    }

    fn section(id: u32, title: &str) -> Value {
        json!({ "kind": "section", "id": format!("SEC-{id:03}"), "title": title })
    }

    /// A leaf MUST requirement whose body states its modality.
    fn requirement(id: u32, title: &str) -> Value {
        json!({
            "kind": "requirement",
            "id": format!("REQ-{id:03}"),
            "title": title,
            "body": format!("{title} MUST hold."),
            "modality": "MUST",
        })
    }

    fn term(id: u32, title: &str, definition: &str) -> Value {
        json!({
            "kind": "term",
            "id": format!("TERM-{id:03}"),
            "title": title,
            "definition": definition,
        })
    }

    /// `node` with `fields` set.
    fn with(mut node: Value, fields: Value) -> Value {
        let node_fields = node.as_object_mut().unwrap();
        for (key, value) in fields.as_object().unwrap() {
            node_fields.insert(key.clone(), value.clone());
        }
        node
    }

    /// What renders between the root's heading and the Glossary's anchor,
    /// for a root without a body.
    fn middle(rendered: &str) -> &str {
        let start = rendered.find("# Root\n\n").expect("the root heading") + "# Root\n\n".len();
        let end = rendered
            .find(r#"<a id="SEC-900"></a>"#)
            .expect("the Glossary's anchor");
        rendered[start..end].trim_end()
    }

    fn parse(markdown: &str) -> Parser<'_> {
        Parser::new_ext(
            markdown,
            Options::ENABLE_STRIKETHROUGH | Options::ENABLE_TABLES,
        )
    }

    /// Each heading's level and text, in order.
    fn headings(markdown: &str) -> Vec<(usize, String)> {
        let mut headings = Vec::new();
        let mut current: Option<(usize, String)> = None;
        for event in parse(markdown) {
            match event {
                Event::Start(Tag::Heading { level, .. }) => {
                    current = Some((heading_level(level), String::new()));
                }
                Event::Text(text) | Event::Code(text) => {
                    if let Some((_, heading)) = &mut current {
                        heading.push_str(&text);
                    }
                }
                Event::End(pulldown_cmark::TagEnd::Heading(_)) => {
                    headings.extend(current.take());
                }
                _ => {}
            }
        }
        headings
    }

    fn heading_level(level: HeadingLevel) -> usize {
        match level {
            HeadingLevel::H1 => 1,
            HeadingLevel::H2 => 2,
            HeadingLevel::H3 => 3,
            HeadingLevel::H4 => 4,
            HeadingLevel::H5 => 5,
            HeadingLevel::H6 => 6,
        }
    }

    /// The IDs of the anchors in `markdown`'s raw HTML, in order.
    fn anchors(markdown: &str) -> Vec<String> {
        const OPEN: &str = r#"<a id=""#;
        let mut anchors = Vec::new();
        for event in parse(markdown) {
            let (Event::Html(html) | Event::InlineHtml(html)) = event else {
                continue;
            };
            let mut rest = &*html;
            while let Some(start) = rest.find(OPEN) {
                rest = &rest[start + OPEN.len()..];
                let end = rest.find('"').expect("a closing quote");
                anchors.push(rest[..end].to_owned());
                rest = &rest[end..];
            }
        }
        anchors
    }

    /// The destinations of `markdown`'s links, in order.
    fn link_targets(markdown: &str) -> Vec<String> {
        parse(markdown)
            .filter_map(|event| match event {
                Event::Start(Tag::Link { dest_url, .. }) => Some(dest_url.to_string()),
                _ => None,
            })
            .collect()
    }

    /// The text a reader sees, outside raw HTML.
    fn visible_text(markdown: &str) -> String {
        let texts: Vec<String> = parse(markdown)
            .filter_map(|event| match event {
                Event::Text(text) | Event::Code(text) => Some(text.to_string()),
                _ => None,
            })
            .collect();
        texts.join("\n")
    }

    /// The ID of every node in `graph`, the Glossary's included.
    fn node_ids(graph: &SlcrRequirementsDocument) -> Vec<String> {
        let requirements = graph.requirements();
        let sections = graph.sections().into_iter().map(|s| s.id().to_string());
        let glossary = [graph.glossary().id().to_string()];
        let reqs = requirements.iter().map(|r| r.id().to_string());
        let criteria = requirements
            .iter()
            .flat_map(|r| r.acceptance_criteria())
            .map(|c| c.id().to_string());
        let terms = graph.glossary().terms().iter().map(|t| t.id().to_string());
        let mut ids: Vec<String> = sections
            .chain(glossary)
            .chain(reqs)
            .chain(criteria)
            .chain(terms)
            .collect();
        ids.sort();
        ids
    }

    /// Assert what holds of every rendered document: one anchor for every
    /// node and no other, every link resolving to one, headings no deeper
    /// than H6, no ID in the visible text, and clean text.
    fn assert_well_formed(graph: &SlcrRequirementsDocument) {
        let rendered = document(graph);

        let anchors = anchors(&rendered);
        let unique: HashSet<&str> = anchors.iter().map(String::as_str).collect();
        assert_eq!(unique.len(), anchors.len(), "anchors repeat");
        let mut sorted = anchors.clone();
        sorted.sort();
        assert_eq!(sorted, node_ids(graph));

        for target in link_targets(&rendered) {
            let id = target.strip_prefix('#').expect("an intra-document link");
            assert!(unique.contains(id), "{target} resolves to nothing");
        }

        let headings = headings(&rendered);
        assert!(headings.iter().all(|(level, _)| *level <= DEEPEST_HEADING));
        assert_eq!(headings[0], (1, graph.root().title().to_string()));

        let text = visible_text(&rendered);
        for prefix in ["SEC-", "REQ-", "TERM-", "AC-"] {
            assert!(!text.contains(prefix), "an ID is visible: {text}");
        }

        assert!(!rendered.contains('\r'));
        assert!(rendered.ends_with('\n') && !rendered.ends_with("\n\n"));
        assert!(is_rendered(rendered.as_bytes()));
    }

    /// A larger document using every construct: Sections nested two deep,
    /// three chains of requirements each nested seven deep, below the
    /// deepest heading, where each refines its container; refinements and
    /// dependencies across chains; terms with aliases; and criteria.
    fn synthetic() -> SlcrRequirementsDocument {
        const CHAINS: u32 = 3;
        const LENGTH: u32 = 7;
        let id = |chain: u32, level: u32| chain * LENGTH + level + 1;
        let mut criteria = 0;
        let mut top_sections = Vec::new();
        for chain in 0..CHAINS {
            let mut node: Option<Value> = None;
            for level in (0..LENGTH).rev() {
                let mut requirement =
                    requirement(id(chain, level), &format!("Chain {chain} level {level}"));
                let mut refines = Vec::new();
                if level > 0 {
                    refines.push(json!(format!("REQ-{:03}", id(chain, level - 1))));
                }
                if level + 1 < LENGTH {
                    requirement["refinement"] = json!("AND");
                }
                if level + 1 == LENGTH && chain > 0 {
                    refines.push(json!(format!("REQ-{:03}", id(chain - 1, 0))));
                }
                if level == 0 && chain + 1 < CHAINS {
                    // The next chain's deepest requirement refines this one.
                    requirement["refinement"] = json!("AND");
                }
                if !refines.is_empty() {
                    requirement["refines"] = json!(refines);
                }
                if level == 3 && chain > 0 {
                    requirement["dependsOn"] = json!([
                        format!("SEC-{:03}", chain + 1),
                        format!("REQ-{:03}", id(chain - 1, 2)),
                    ]);
                }
                if level == 1 {
                    requirement["usesTerm"] = json!([format!("TERM-{:03}", chain + 1)]);
                }
                if level == 2 {
                    let mut list = Vec::new();
                    for title in ["First criterion", "Second criterion"] {
                        criteria += 1;
                        list.push(json!({
                            "kind": "acceptanceCriterion",
                            "id": format!("AC-{criteria:03}"),
                            "title": title,
                            "body": "Done looks like this.\n\n```text\nsketch\n```",
                        }));
                    }
                    requirement["acceptanceCriteria"] = json!(list);
                }
                if let Some(child) = node.take() {
                    requirement["children"] = json!([child]);
                }
                node = Some(requirement);
            }
            let inner = with(
                section(chain + 5, &format!("Chain {chain} details")),
                json!({ "body": "Background.", "children": [node.unwrap()] }),
            );
            top_sections.push(with(
                section(chain + 2, &format!("Chain {chain}")),
                json!({ "usesTerm": [format!("TERM-{:03}", chain + 1)], "children": [inner] }),
            ));
        }
        let terms = json!([
            with(
                term(1, "zeta", "The last letter."),
                json!({ "aliases": ["Z"] })
            ),
            term(2, "Alpha", "The first letter.\n\nIt comes first."),
            term(3, "beta", "The second letter."),
        ]);
        spec(json!(top_sections), terms)
    }

    #[test]
    fn the_canon_example_renders_exactly() {
        assert_eq!(document(&canon()), TODO_API_MD);
    }

    #[test]
    fn every_format_of_the_canon_example_renders_the_same_bytes() {
        for (format, source) in [
            (Format::Json, TODO_API_JSON),
            (Format::Yaml, TODO_API_YAML),
            (Format::Toml, TODO_API_TOML),
        ] {
            let graph: SlcrRequirementsDocument = format
                .parse(Path::new("todo-api"), source.to_owned())
                .unwrap();
            assert_eq!(document(&graph), TODO_API_MD, "{format}");
        }
    }

    #[test]
    fn rendering_is_deterministic() {
        for graph in [canon(), synthetic()] {
            let rendered = document(&graph);
            assert_eq!(document(&graph), rendered);
            assert_eq!(document(&graph.clone()), rendered);
            for format in [Format::Json, Format::Yaml, Format::Toml] {
                let serialized = format.serialize(&graph).unwrap();
                let reloaded: SlcrRequirementsDocument =
                    format.parse(Path::new("spec"), serialized).unwrap();
                assert_eq!(document(&reloaded), rendered, "{format}");
            }
        }
    }

    #[test]
    fn the_canon_example_is_well_formed() {
        assert_well_formed(&canon());
    }

    #[test]
    fn a_large_document_is_well_formed() {
        assert_well_formed(&synthetic());
    }

    #[test]
    fn a_new_document_renders_its_root_and_glossary() {
        let graph = SlcrRequirementsDocument::new(
            SpecName::try_from("todo-api".to_owned()).unwrap(),
            Title::try_from("TodoList API".to_owned()).unwrap(),
        );
        assert_eq!(
            document(&graph),
            "<!-- Generated by slcr from the todo-api specification. Do not edit: change the \
             specification and run `slcr render`. -->\n\
             \n\
             <a id=\"SEC-001\"></a>\n\
             # TodoList API\n\
             \n\
             <a id=\"SEC-002\"></a>\n\
             ## 1. Glossary\n"
        );
        assert_well_formed(&graph);
    }

    #[test]
    fn the_canon_example_headings_follow_containment() {
        let expected = [
            (1, "TodoList API"),
            (2, "1. Views"),
            (3, "1.1 TodoListItem endpoint"),
            (4, "1.1.1 POST creates an item"),
            (5, "1.1.1.1 Request is authenticated"),
            (4, "1.1.2 GET reads an item"),
            (2, "2. Controllers"),
            (3, "2.1 TodoListItem controller"),
            (4, "2.1.1 Validates the request payload"),
            (2, "3. Models"),
            (3, "3.1 Table todo_list_item exists"),
            (2, "4. Authentication"),
            (3, "4.1 Accepts authentication tokens"),
            (4, "4.1.1 Accepts OAuth tokens"),
            (4, "4.1.2 Accepts API keys"),
            (2, "5. Glossary"),
        ]
        .map(|(level, text)| (level, text.to_owned()));
        assert_eq!(headings(&document(&canon())), expected);
    }

    #[test]
    fn rendered_documents_are_marked_as_rendered() {
        assert!(is_rendered(TODO_API_MD.as_bytes()));
        assert!(is_rendered(
            b"<!-- Generated by slcr from the billing specification. -->\n"
        ));
        for contents in [
            &b""[..],
            b"# Hand-written\n",
            b"<!-- Generated by something else -->\n",
            b"\n<!-- Generated by slcr from the todo-api specification. -->\n",
            b"<!-- Generated by slcr",
        ] {
            assert!(
                !is_rendered(contents),
                "{:?}",
                String::from_utf8_lossy(contents)
            );
        }
    }

    #[test]
    fn numbers_are_dotted() {
        assert_eq!(Number::default().to_string(), "");
        assert_eq!(Number(vec![2]).to_string(), "2.");
        assert_eq!(Number(vec![2, 1]).to_string(), "2.1");
        assert_eq!(Number(vec![2, 1, 13]).to_string(), "2.1.13");
        assert_eq!(Number::default().child(3).child(1), Number(vec![3, 1]));
        assert_eq!(Number(vec![3, 1]).depth(), 2);
    }

    #[test]
    fn sections_and_requirements_are_numbered_in_one_sequence() {
        let graph = spec(
            json!([
                with(
                    section(2, "A"),
                    json!({ "children": [requirement(1, "B")] })
                ),
                // Nested without refining: a sub-heading all the same.
                with(
                    requirement(2, "C"),
                    json!({ "children": [requirement(3, "D")] })
                ),
                section(3, "E"),
            ]),
            json!([]),
        );
        let expected = [
            (1, "Root"),
            (2, "1. A"),
            (3, "1.1 B"),
            (2, "2. C"),
            (3, "2.1 D"),
            (2, "3. E"),
            (2, "4. Glossary"),
        ]
        .map(|(level, text)| (level, text.to_owned()));
        assert_eq!(headings(&document(&graph)), expected);
    }

    #[test]
    fn nodes_below_the_deepest_heading_are_bold_numbered_paragraphs() {
        let mut node = requirement(6, "Depth 7");
        for (id, title) in [
            (5, "Depth 6"),
            (4, "Depth 5"),
            (3, "Depth 4"),
            (2, "Depth 3"),
            (1, "Depth 2"),
        ] {
            node = with(requirement(id, title), json!({ "children": [node] }));
        }
        let graph = spec(
            json!([with(section(2, "Depth 1"), json!({ "children": [node] }))]),
            json!([]),
        );
        let rendered = document(&graph);
        assert!(
            rendered.contains(
                "<a id=\"REQ-004\"></a>\n\
                 ###### 1.1.1.1.1 Depth 5\n\
                 \n\
                 Depth 5 MUST hold.\n\
                 \n\
                 <a id=\"REQ-005\"></a>\n\
                 **1.1.1.1.1.1 Depth 6**\n\
                 \n\
                 Depth 6 MUST hold.\n\
                 \n\
                 <a id=\"REQ-006\"></a>\n\
                 **1.1.1.1.1.1.1 Depth 7**\n\
                 \n\
                 Depth 7 MUST hold.\n"
            ),
            "{rendered}"
        );
        let deepest = headings(&rendered)
            .into_iter()
            .map(|(level, _)| level)
            .max();
        assert_eq!(deepest, Some(DEEPEST_HEADING));
        assert_well_formed(&graph);
    }

    #[test]
    fn a_requirement_renders_every_part_in_order() {
        let controller = with(
            requirement(3, "Item controller"),
            json!({
                "rationale": "Requests need handling.",
                "refinement": "XOR",
                "refines": ["REQ-002"],
                "dependsOn": ["SEC-002", "REQ-001"],
                "usesTerm": ["TERM-001"],
                "acceptanceCriteria": [
                    {
                        "kind": "acceptanceCriterion",
                        "id": "AC-001",
                        "title": "Controller is declared",
                        "body": "A controller class exists."
                    },
                    {
                        "kind": "acceptanceCriterion",
                        "id": "AC-002",
                        "title": "Payload is validated",
                        "body": "Invalid payloads are rejected."
                    }
                ],
                "children": [
                    with(requirement(4, "JSON payload"), json!({
                        "body": "It MAY accept JSON.", "modality": "MAY", "refines": ["REQ-003"]
                    })),
                    with(requirement(5, "Form payload"), json!({
                        "body": "It MAY accept forms.", "modality": "MAY", "refines": ["REQ-003"]
                    })),
                ]
            }),
        );
        let graph = spec(
            json!([
                with(
                    section(2, "Models"),
                    json!({
                        "body": "Models preamble.", "children": [requirement(1, "Item table")]
                    })
                ),
                with(
                    requirement(2, "Item endpoint"),
                    json!({ "refinement": "AND" })
                ),
                controller,
            ]),
            json!([term(1, "Item", "A thing to do.")]),
        );
        let rendered = document(&graph);
        assert_eq!(
            middle(&rendered),
            "<a id=\"SEC-002\"></a>\n\
             ## 1. Models\n\
             \n\
             Models preamble.\n\
             \n\
             <a id=\"REQ-001\"></a>\n\
             ### 1.1 Item table\n\
             \n\
             Item table MUST hold.\n\
             \n\
             <a id=\"REQ-002\"></a>\n\
             ## 2. Item endpoint\n\
             \n\
             Item endpoint MUST hold.\n\
             \n\
             All of the following must hold:\n\
             \n\
             - [Item controller](#REQ-003)\n\
             \n\
             <a id=\"REQ-003\"></a>\n\
             ## 3. Item controller\n\
             \n\
             Item controller MUST hold.\n\
             \n\
             *Rationale:* Requests need handling.\n\
             \n\
             Exactly one of the following must hold:\n\
             \n\
             - [JSON payload](#REQ-004)\n\
             - [Form payload](#REQ-005)\n\
             \n\
             *Refines:* [Item endpoint](#REQ-002)\n\
             \n\
             *Depends on:* [Models](#SEC-002), [Item table](#REQ-001)\n\
             \n\
             *Terms:* [Item](#TERM-001)\n\
             \n\
             *Acceptance criteria:*\n\
             \n\
             <a id=\"AC-001\"></a>**Controller is declared**\n\
             \n\
             A controller class exists.\n\
             \n\
             <a id=\"AC-002\"></a>**Payload is validated**\n\
             \n\
             Invalid payloads are rejected.\n\
             \n\
             <a id=\"REQ-004\"></a>\n\
             ### 3.1 JSON payload\n\
             \n\
             It MAY accept JSON.\n\
             \n\
             <a id=\"REQ-005\"></a>\n\
             ### 3.2 Form payload\n\
             \n\
             It MAY accept forms."
        );
        assert_well_formed(&graph);
    }

    #[test]
    fn a_leaf_requirement_renders_no_empty_parts() {
        let graph = spec(json!([requirement(1, "Leaf")]), json!([]));
        assert_eq!(
            middle(&document(&graph)),
            "<a id=\"REQ-001\"></a>\n## 1. Leaf\n\nLeaf MUST hold."
        );
    }

    #[test]
    fn each_refinement_has_its_sentence() {
        for (refinement, sentence) in [
            ("AND", "All of the following must hold:"),
            ("OR", "At least one of the following must hold:"),
            ("XOR", "Exactly one of the following must hold:"),
        ] {
            let graph = spec(
                json!([with(
                    requirement(1, "Parent"),
                    json!({
                        "refinement": refinement,
                        "children": [
                            with(requirement(2, "First"), json!({ "refines": ["REQ-001"] })),
                            with(requirement(3, "Second"), json!({ "refines": ["REQ-001"] })),
                        ]
                    })
                )]),
                json!([]),
            );
            let expected = format!(
                "Parent MUST hold.\n\n{sentence}\n\n- [First](#REQ-002)\n- [Second](#REQ-003)\n\n"
            );
            assert!(document(&graph).contains(&expected), "{refinement}");
        }
    }

    #[test]
    fn the_refinement_sentence_covers_every_refiner_and_no_other_child() {
        let graph = spec(
            json!([
                // Housed before its parent, so it is listed first.
                with(requirement(5, "Earlier"), json!({ "refines": ["REQ-001"] })),
                with(
                    requirement(1, "Parent"),
                    json!({
                        "refinement": "AND",
                        "children": [
                            with(requirement(2, "Nested refiner"), json!({ "refines": ["REQ-001"] })),
                            // Nested to elaborate, but refining nothing.
                            requirement(3, "Nested elaboration"),
                        ]
                    })
                ),
                with(
                    section(2, "Elsewhere"),
                    json!({ "children": [
                    with(requirement(4, "Housed elsewhere"), json!({ "refines": ["REQ-001"] })),
                ] })
                ),
            ]),
            json!([]),
        );
        let rendered = document(&graph);
        assert!(
            rendered.contains(
                "All of the following must hold:\n\
                 \n\
                 - [Earlier](#REQ-005)\n\
                 - [Nested refiner](#REQ-002)\n\
                 - [Housed elsewhere](#REQ-004)\n\
                 \n\
                 <a id=\"REQ-002\"></a>\n"
            ),
            "{rendered}"
        );
        assert!(rendered.contains("<a id=\"REQ-003\"></a>\n### 2.2 Nested elaboration\n"));
        assert!(!rendered.contains("- [Nested elaboration]"));
    }

    #[test]
    fn the_refines_line_omits_only_the_containment_parent() {
        let graph = spec(
            json!([
                with(
                    requirement(1, "Parent"),
                    json!({
                        "refinement": "AND",
                        "children": [
                            with(requirement(2, "Both"), json!({ "refines": ["REQ-003", "REQ-001"] })),
                            with(requirement(4, "Other only"), json!({ "refines": ["REQ-003"] })),
                            with(requirement(5, "Parent only"), json!({ "refines": ["REQ-001"] })),
                        ]
                    })
                ),
                with(requirement(3, "Other"), json!({ "refinement": "OR" })),
                with(
                    section(2, "Section"),
                    json!({ "children": [
                    with(requirement(6, "Under a section"), json!({ "refines": ["REQ-001"] })),
                ] })
                ),
            ]),
            json!([]),
        );
        let rendered = document(&graph);
        let refines_line = |title: &str| {
            let block = rendered.split(&format!(" {title}\n\n")).nth(1).unwrap();
            let next = block.find("\n\n<a id=").unwrap_or(block.len());
            block[..next]
                .lines()
                .find(|line| line.starts_with("*Refines:*"))
                .map(str::to_owned)
        };
        assert_eq!(
            refines_line("Both").as_deref(),
            Some("*Refines:* [Other](#REQ-003)")
        );
        assert_eq!(
            refines_line("Other only").as_deref(),
            Some("*Refines:* [Other](#REQ-003)")
        );
        assert_eq!(refines_line("Parent only"), None);
        assert_eq!(
            refines_line("Under a section").as_deref(),
            Some("*Refines:* [Parent](#REQ-001)")
        );
    }

    #[test]
    fn dependencies_link_sections_requirements_and_the_glossary_in_order() {
        let graph = spec(
            json!([
                with(
                    section(2, "Models"),
                    json!({ "children": [requirement(1, "Table")] })
                ),
                with(
                    requirement(2, "Controller"),
                    json!({
                        "dependsOn": ["REQ-001", "SEC-900", "SEC-002"]
                    })
                ),
            ]),
            json!([]),
        );
        assert!(document(&graph).contains(
            "*Depends on:* [Table](#REQ-001), [Glossary](#SEC-900), [Models](#SEC-002)\n"
        ));
    }

    #[test]
    fn sections_render_their_body_and_terms_before_their_children() {
        let graph = spec(
            json!([with(
                section(2, "Models"),
                json!({
                    "body": "Persistence assumptions.",
                    "usesTerm": ["TERM-002", "TERM-001"],
                    "children": [requirement(1, "Table")]
                })
            )]),
            json!([term(1, "Row", "A record."), term(2, "Table", "Rows.")]),
        );
        assert_eq!(
            middle(&document(&graph)),
            "<a id=\"SEC-002\"></a>\n\
             ## 1. Models\n\
             \n\
             Persistence assumptions.\n\
             \n\
             *Terms:* [Table](#TERM-002), [Row](#TERM-001)\n\
             \n\
             <a id=\"REQ-001\"></a>\n\
             ### 1.1 Table\n\
             \n\
             Table MUST hold."
        );
    }

    #[test]
    fn the_root_renders_its_body_and_terms() {
        let mut value = spec_value(json!([]), json!([term(1, "API", "An interface.")]));
        value["root"]["body"] = json!("The introduction.");
        value["root"]["usesTerm"] = json!(["TERM-001"]);
        let graph: SlcrRequirementsDocument = serde_json::from_value(value).unwrap();
        assert!(document(&graph).contains(
            "# Root\n\nThe introduction.\n\n*Terms:* [API](#TERM-001)\n\n<a id=\"SEC-900\"></a>\n"
        ));
    }

    #[test]
    fn prose_is_kept_exactly_apart_from_line_endings_and_surrounding_whitespace() {
        let body = "\r\n\r\nIt MUST hold.\r\n\r\n\r\n```datalog\r\nverified(R).\r\n\r\n\tnested(\"tab\").\r\n```\r\n\r\n  ";
        let graph = spec(
            json!([with(
                requirement(1, "Exact"),
                json!({
                    "body": body,
                    "rationale": "Because.\r\n\r\nReally.  \r\n",
                    "acceptanceCriteria": [{
                        "kind": "acceptanceCriterion",
                        "id": "AC-001",
                        "title": "Sketched",
                        "body": "Like this:\n\n    indented code\n"
                    }]
                })
            )]),
            json!([]),
        );
        let rendered = document(&graph);
        assert_eq!(
            middle(&rendered),
            "<a id=\"REQ-001\"></a>\n\
             ## 1. Exact\n\
             \n\
             It MUST hold.\n\
             \n\
             \n\
             ```datalog\n\
             verified(R).\n\
             \n\
             \tnested(\"tab\").\n\
             ```\n\
             \n\
             *Rationale:* Because.\n\
             \n\
             Really.\n\
             \n\
             *Acceptance criteria:*\n\
             \n\
             <a id=\"AC-001\"></a>**Sketched**\n\
             \n\
             Like this:\n\
             \n    \
             indented code"
        );
        let code: Vec<String> = parse(&rendered)
            .filter_map(|event| match event {
                Event::Text(text) => Some(text.to_string()),
                _ => None,
            })
            .filter(|text| text.contains("verified") || text.contains("indented"))
            .collect();
        assert_eq!(
            code,
            ["verified(R).\n\n\tnested(\"tab\").\n", "indented code\n"]
        );
        assert!(!rendered.contains('\r'));
    }

    #[test]
    fn whitespace_only_prose_is_left_out() {
        let graph = spec(
            json!([with(
                requirement(1, "Blank"),
                json!({ "body": " \n\t", "rationale": "\r\n" })
            )]),
            json!([]),
        );
        assert_eq!(
            middle(&document(&graph)),
            "<a id=\"REQ-001\"></a>\n## 1. Blank"
        );
    }

    #[test]
    fn titles_are_escaped_wherever_they_appear() {
        let title = "Use *stars* & <tags>";
        let escaped = r"Use \*stars\* \& \<tags\>";
        let graph = spec(
            json!([
                with(
                    requirement(1, title),
                    json!({
                        "refinement": "AND",
                        "acceptanceCriteria": [{
                            "kind": "acceptanceCriterion", "id": "AC-001", "title": title, "body": "Done."
                        }]
                    })
                ),
                with(requirement(2, "Child"), json!({ "refines": ["REQ-001"] })),
            ]),
            json!([with(
                term(1, title, "A term."),
                json!({ "aliases": ["[alias]"] })
            )]),
        );
        let rendered = document(&graph);
        assert!(rendered.contains(&format!("## 1. {escaped}\n")));
        assert!(rendered.contains(&format!("<a id=\"AC-001\"></a>**{escaped}**\n")));
        assert!(rendered.contains(&format!("*Refines:* [{escaped}](#REQ-001)\n")));
        assert!(
            rendered.contains("<dt><a id=\"TERM-001\"></a>Use *stars* &amp; &lt;tags&gt;</dt>\n")
        );
        assert!(rendered.contains("*Also called:* \\[alias\\]\n"));
        assert_well_formed(&graph);
    }

    #[test]
    fn modality_is_never_rendered_as_metadata() {
        let graph = spec(
            json!([with(
                requirement(1, "Quiet"),
                json!({
                    "modality": "MUST NOT", "body": "Nothing is logged."
                })
            )]),
            json!([]),
        );
        let rendered = document(&graph);
        assert!(!rendered.contains("MUST"), "{rendered}");
        assert!(!rendered.contains("NOT"), "{rendered}");
    }

    #[test]
    fn the_glossary_renders_as_a_definition_list() {
        let mut value = spec_value(
            json!([]),
            json!([
                with(
                    term(
                        1,
                        "Slice",
                        "A requirement plus its context.\n\nSee *section 9*."
                    ),
                    json!({ "aliases": ["Agent slice", "Context slice"] })
                ),
                term(2, "R&D <team>", "The builders."),
            ]),
        );
        value["glossary"]["body"] = json!("Terms used below.");
        let graph: SlcrRequirementsDocument = serde_json::from_value(value).unwrap();
        let rendered = document(&graph);
        let glossary = &rendered[rendered.find(r#"<a id="SEC-900"></a>"#).unwrap()..];
        assert_eq!(
            glossary,
            "<a id=\"SEC-900\"></a>\n\
             ## 1. Glossary\n\
             \n\
             Terms used below.\n\
             \n\
             <dl>\n\
             <dt><a id=\"TERM-002\"></a>R&amp;D &lt;team&gt;</dt>\n\
             <dd>\n\
             \n\
             The builders.\n\
             \n\
             </dd>\n\
             <dt><a id=\"TERM-001\"></a>Slice</dt>\n\
             <dd>\n\
             \n\
             *Also called:* Agent slice, Context slice\n\
             \n\
             A requirement plus its context.\n\
             \n\
             See *section 9*.\n\
             \n\
             </dd>\n\
             </dl>\n"
        );
        // Definitions are Markdown, not swallowed by the surrounding HTML.
        let emphasized = parse(glossary)
            .filter(|event| matches!(event, Event::Start(Tag::Emphasis)))
            .count();
        assert_eq!(emphasized, 2);
        assert_well_formed(&graph);
    }

    #[test]
    fn glossary_terms_are_alphabetized_ignoring_case_then_by_id() {
        let graph = spec(
            json!([]),
            json!([
                term(1, "beta", "B."),
                term(2, "Alpha", "A."),
                term(3, "alpha", "a."),
                term(4, "Gamma", "G."),
                term(5, "alpha", "a again."),
            ]),
        );
        let terms: Vec<String> = anchors(&document(&graph))
            .into_iter()
            .filter(|id| id.starts_with("TERM-"))
            .collect();
        assert_eq!(
            terms,
            ["TERM-002", "TERM-003", "TERM-005", "TERM-001", "TERM-004"]
        );
    }

    #[test]
    fn an_empty_glossary_renders_only_its_heading_and_body() {
        let mut value = spec_value(json!([]), json!([]));
        value["glossary"]["body"] = json!("No terms yet.");
        let graph: SlcrRequirementsDocument = serde_json::from_value(value).unwrap();
        let rendered = document(&graph);
        assert!(
            rendered.ends_with("<a id=\"SEC-900\"></a>\n## 1. Glossary\n\nNo terms yet.\n"),
            "{rendered}"
        );
        assert!(!rendered.contains("<dl>"));
    }

    #[test]
    fn an_unchecked_document_renders_dangling_references_as_ids() {
        let value = spec_value(
            json!([
                // REQ-002 refines REQ-001, which lacks a `refinement`.
                requirement(1, "Unrefined"),
                with(
                    requirement(2, "Dangling"),
                    json!({
                        "refines": ["REQ-001", "REQ-099"],
                        "dependsOn": ["SEC-099", "REQ-098"],
                        "usesTerm": ["TERM-099"]
                    })
                ),
            ]),
            json!([]),
        );
        let unchecked: UncheckedDocument = serde_json::from_value(value).unwrap();
        assert!(!unchecked.report().violations().is_empty());
        let rendered = document(unchecked.document());
        assert!(
            rendered.contains(
                "*Refines:* [Unrefined](#REQ-001), REQ-099\n\
                 \n\
                 *Depends on:* SEC-099, REQ-098\n\
                 \n\
                 *Terms:* TERM-099\n"
            ),
            "{rendered}"
        );
        assert!(!rendered.contains("must hold"));
    }
}
